### ISSUE TITLE
Compiling C

### ISSUE THREAD

**Issue by kcaisley** [hansk68/Embedded-System-Lab#3]
https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/b3319490978ae72fcac03aa423c166c1bcb08b7b/docs/source/software-intro.rst?plain=1#L50

In this section, the 'Run without debug' command wasn't automatically compiling the code automatically. Manually running the Build worked.

![image](https://user-images.githubusercontent.com/112255410/235641942-0a69c120-54ac-4cd3-905a-fa6a6471dc04.png)

Also, the shortcut for running the build task appears to be `F7` not `Ctrl+Shift+b`?

![Screenshot from 2023-05-02 12-25-13](https://user-images.githubusercontent.com/112255410/235645429-0840143a-2c7f-4f7b-963d-bb271663a949.png)

**Comment by hansk68** [comment]
I have added a more precise explanation in the software environment introduction. For c-code first:
  - build project: ctrl+b or Terminal->Run Build task and then 
  - run executable from within VC: ctrl+F5 or Run->Run without debugging.
