### ISSUE TITLE
RPi Memory Address Offsets

### ISSUE THREAD

**Issue by kcaisley** [hansk68/Embedded-System-Lab#4]
https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/309655a70c4c55c979565f3b0f6a628edbe61f89/docs/source/hardware-intro.rst?plain=1#L51-L62

I think the information is a bit too specific here, if the students will only be working with an RPi 4? Is there a chance that some students will end up using different models?

**Comment by hansk68** [comment]
I decided to keep the table to point out possible issues with hw compatibility if this would be overlooked.
