### ISSUE TITLE
GPIO Introduction

### ISSUE THREAD

**Issue by kcaisley** [hansk68/Embedded-System-Lab#5]
https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/309655a70c4c55c979565f3b0f6a628edbe61f89/docs/source/gpio.rst?plain=1#L6

Perhaps more emphasis on that fact that GPIOs are driver circuits, on the periphery of the chip, which monitor arriving data signals and transmit outgoing data signals? I recall, when I was first learning, not understanding why special circuits were needed for this, as issues of drive strength and voltage swing weren't clear.

**Comment by hansk68** [comment]
Added some more explanation of the GPIO circuit.
