### ISSUE TITLE
Change suggestions for SMU exercises.

### ISSUE THREAD

**Issue by rleiser1995** [hansk68/Embedded-System-Lab#7]
As discussed, here are the issues that confused Tobias and me when we were doing the exercises:

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L103 

Maybe it would be good to mention that there is no single "correct" definition of these. Maybe a wording like `Research what specific meaning the terms accuracy, precision and resolution have in the context of analog to digital converters`. Or maybe not, because the next question is rather concretely about ADCs.

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L104 

Here it would be good to either specify the estimate that is to be derived ($\frac{1}{\sqrt{12}}$) or be more precises about what quantization error is to be estimated (`Find a lower bound for the root-mean-square measurement error (i.e. the standard deviation) based only on the value of a LSB`).

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L106

About the part with choosing $R_\text{SNS}$, maybe it would be good to say `If you could choose an arbitrary value for the current sense resistor |RSNS|, which would give you the best possible measurement range?`

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L108 

Should say `ratio 1:100:10.000`.

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L116 

We didn't know what is meant by a level 2 model, so it is maybe better to call it something like `...the quadratic model for the saturation region`. Or, either give the expression of the model or link to it on [Wikipedia](https://en.wikipedia.org/wiki/MOSFET#Saturation_or_active_mode). However, the Wikipedia article also has the solution to the following exercise.

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L126

Maybe this exercise could explicitly ask to plot the curves `overlaid` or `overlapping` in a single plot. We thought `combine` meant to concatenate the data so that only a single trace would be drawn.

- https://github.com/SiLab-Bonn/Embedded-System-Lab/blob/0176bb9171c51a0a84e0a919f5288d5abbe4f5d2/docs/source/smu.rst?plain=1#L134

It would be fun to also ask students to determine (or estimate) the forward voltage. It was not so obvious to us what a good answer about the part with the resistors could be.

**Comment by hansk68** [comment]
I have implemented (most of) the suggestions and partially re-phrased the text.
