### ISSUE TITLE
AFE Exercises 0-2

### ISSUE THREAD

**Issue by rleiser1995** [hansk68/Embedded-System-Lab#9]
After going through the Exercises 0, 1 and 2, Tobias and I had the following Ideas

- Exercise 0.2: We didn't know what the charge transfer gain is. We suspect it should be unit-less but the only candidate we could think of is $\frac{1}{C_f}$.
- Exercise 0.6 wasn't very clear to us at all. Do we create a histogram by sampling the output of the frontend in regular intervals? Or once after triggered injections? Isn't the modified histogram just a convolution of the original one with the gauss curve?
- Exercise 0.7 asks about purity and efficiency. These should maybe be difend in terms of a confusion matrix because they don't seem to be very common terms. I think, for example, purity could mean $\frac{TP}{TP + FP}$ and efficiency $\frac{TN}{TN + FN}$.
- Exercise 1.1: We both thought that there's not really an advantage to implement a script with threading as we didn't really see the advantage over changing values and re running a single script. This is especially so, since we will want to build our future scans based on the very first script.
- Exercise 1.2 Maybe  
    > What time constants do you have to take into account to estimate the maximum injection frequency?

    should be changed, because the only time constant you have to take into account is *the* time constant. Maybe 
    > Which circuit parameters do you have to take into account to estimate the maximum injection frequency?
- Exercise 1.1 and 1.3: These seem rather similar and can probably be merged. 
- Exercise 1 could use an additional exercise which would come in very handy later. Something like 
    > 3.5 Make a small table of DAC values for __VINJ__ vs. peak voltages measured after the shaping amplifier. Also calculate which __VTHR__ DAC value would be just able to still discriminate this signal. The table will be useful for setting reasonable parameters in later exercises.

    Such a table would have helped a lot in Exercise 2.3.
- Exercise 2.1 maybe doesn't need to mention automated measurement, as in this experiment the measurements will be done by hand. Maybe there could be a hint to use an external oscilloscope for pulse width measurements, and/or the exercise could specify that only 5-10 different values need to be considered. For us, the main takeaway was that the relationship is non-linear but concave, is there something else to be found out?

**Comment by hansk68** [comment]
Thanks! Implemented (most of it).
